version: '2'
services:
  db:
    container_name: 'nyarchive_database'
    image: 'mariadb'
    environment: 
      MARIADB_ROOT_PASSWORD: '' #Root-Passwort eintragen
      MARIADB_DATABASE: 'nyarchive'
    volumes:
      - ':/var/lib/mysql/' #Persistenten DB-Pfad eintragen
    ports:
      - 3306:3306
  api:
    container_name: 'nyarchive_api'
    build:
      context: ../nyarchive
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '127.10.0.1:443:443' #Host-IP:Host-Port:Container-Port
    environment:
      MARIADB_USER: ''
      MARIADB_PASSWORD: ''
      MARIADB_DATABASE: 'nyarchive'